chore: fix for getting commits behind

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -59,14 +59,19 @@ jobs:
         run: |
           main_branch=$(git branch -r --format "%(refname:short)" | grep origin | egrep "master|main" | sed -e 's/origin\///')
           if [ -z "$main_branch" ]; then
-              echo "Main branch not found"
-              exit 1
+            echo "Main branch not found"
+            exit 1
           fi
           git fetch origin $main_branch
-          commits_behind=$(git rev-list --count ${{ github.ref_name }}..$main_branch)
+          git checkout $main_branch
+          git switch -
+          commits_behind=$(git rev-list --count HEAD..$main_branch)
+          commits_ahead=$(git rev-list --count $main_branch..HEAD)
           if [ $commits_behind -gt 0 ]; then
-              echo "Current branch is $commits_behind commits behind $main_branch"
-              exit 1
+            echo "Current branch is $commits_behind commits behind $main_branch"
+            exit 1
+          else
+            echo "Current branch is ahead $commits_ahead commits from $main_branch"
           fi
   plan:
     needs:
