Update workflow to validate only directories with terragrunt.hcl
This change ensures validation runs only in directories containing a `terragrunt.hcl` file. It adds a conditional check to avoid unnecessary validation attempts and improves script resilience. Streamlines the process and avoids errors in irrelevant directories.

diff --git a/.github/workflows/plan.yml b/.github/workflows/plan.yml
--- a/.github/workflows/plan.yml
+++ b/.github/workflows/plan.yml
@@ -204,12 +204,15 @@ jobs:
           changes=$(gh pr view $issue_num --json files --jq ".files.[].path" | sed 's/[^/]*$//' | grep -Ev ".git*|.cloudopsworks" | sort | uniq)
           echo "Changes: $changes"
           for item in $changes; do
-            terragrunt --terragrunt-working-dir $item validate --terragrunt-non-interactive  
-            exit_code=$?
-            echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
-            if [ $exit_code -ne 0 ]; then
-              echo "Error in $item"
-              exit $exit_code
+            # Check there is a terragrunt .hcl file in directory
+            if [ -f "$item/terragrunt.hcl" ]; then
+              terragrunt --terragrunt-working-dir $item validate --terragrunt-non-interactive  
+              exit_code=$?
+              echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
+              if [ $exit_code -ne 0 ]; then
+                echo "Error in $item"
+                exit $exit_code
+              fi
             fi
           done
 
